Add replay recording support
Beamographic/rush pull request #118
Opened 2021-03-25 14:02 UTC by frenzibyte

Currently has to convert from and to legacy replay frames due to no modern replay encoding support osu!lazer-side yet, which limits tertiary and quaternary actions from being saved as-is in replays, but looks to be working as expected to for now.

2021-03-25 15:54 UTC, LumpBloom7 commented
Seeing as rush doesn't record any positional inputs, it would be possible to repurpose one of those values as a bitflag of some sort, similar to mania's implementation. This will make sure the playback matches the actions performed during recording.

2021-03-25 16:15 UTC, frenzibyte commented
Yeah now I realize what you meant back then, will see.

2021-04-10 10:11 UTC, swoolcock requested changes

2021-04-10 10:11 UTC, swoolcock commented on osu.Game.Rulesets.Rush/Replays/RushReplayFrame.cs
> +        private static IEnumerable<RushAction> getActionsFromFlags(RushActionFlags flags)
Likewise for this:
```cs
private static IEnumerable<RushAction> getActionsFromFlags(RushActionFlags flags)
{
    RushActionFlags flag;
    int action = 0;
    while ((flag = (RushActionFlags)(1 << action++)) <= RushActionFlags.LastAction)
    {
        if (flags.HasFlagFast(flag))
            yield return (RushAction)flag;
    }
}
```

If you add to `RushActionFlags` (please do this anyway):

```cs
LastAction = GroundQuaternary
```

2021-04-10 14:29 UTC, frenzibyte commented on osu.Game.Rulesets.Rush/Replays/RushReplayFrame.cs
> +        private static RushActionFlags getFlagsFromActions(IEnumerable<RushAction> actions)
Second one sounds too much there, let's use the first one

2021-04-10 16:44 UTC, merged