Pool HitObjects, explosions and judgements
Beamographic/rush pull request #123
Opened 2021-03-27 19:30 UTC by LumpBloom7

Resolves #59.

I've made pooling work for each HitObject and nested HitObjects, along with explosions, judgements, and the health text. I tried to not touch anything irrelevant or do anything that I would consider out of scope for this PR.

## Encountered problems: 

Some objects and properties aren't lane agnostic, while most objects are fine in this regard, I find the anchor adjustments to be a bit ugly. `MinionPiece` also changes sprites based on the lane the DHO is in, and [I've made it so that it updates its animation set when the DHO has a new applied HitObject](https://github.com/LumpBloom7/rush/blob/4a3484334abd1418d2eec9ab77c0ba3ef35ca99c/osu.Game.Rulesets.Rush/Objects/Drawables/Pieces/MinionPiece.cs#L39). These issues as mentioned early could be completely alleviated with nested playfields.

Next problem I couldn't really get my head around. The `MinionPiece` occasionally appears invisible when proxying is used within `DrawableMinion`, and very inconsistent at that. The `TextureAnimation` drawable is being masked for some reason, and that is worth investigating imo. I've chosen to comment out the proxying code, since that keeps everything functional for now. The whole proxying code can also be removed imo seeing as the HitObjectContainer is reverse-ordered, and that the proxy layer is right on top of HOC, rendering it a redundant procedure.

2021-04-14 23:42 UTC, frenzibyte commented
I've done a thorough review and have pushed preliminary changes for this, looks pretty good. @swoolcock requesting your review and merge.

2021-04-14 23:43 UTC, frenzibyte approved these changes

2021-04-15 00:38 UTC, swoolcock requested changes
Just one small thing.

2021-04-15 00:38 UTC, swoolcock commented on osu.Game.Rulesets.Rush/UI/RushPlayfield.cs
> +            if (laned.Lane == LanedHitLane.Air)
Use playfieldForLane?

2021-04-15 09:09 UTC, swoolcock commented
LGTM

2021-04-15 09:09 UTC, merged