Simplify the way playfield elements are positioned.
Beamographic/rush pull request #150
Opened 2021-05-20 14:49 UTC by LumpBloom7

Fixes #27 as well.

Currently, a grid is used to specify regions for specific playfield elements to be. However, nearly all elements required further positional adjustments via `anchors`, `origins`, `position`, and `padding`, with some of them having a parent container with even more adjustments. This makes it harder to immediately tell where a playfield element would be, when looking at the properties, since they would be inheriting several layers of properties from parents and grandparents.

This PR removes the use of the grid, and reducing the number of parents that can affect positioning of the playfield elements. Most of the positional adjustments are now isolated within the individual playfield elements themselves, rather than being spread out. 

## Differences
* The ground doesn't quite reach the bottom of the screen, stopping right above the progress bar.
* The ground scroll speed now uses the information provided by `IScrollingInfo`, which also fixes the transforms freezing during rewind

## Problems
* The left tile of the ground occasionally spazzes, not sure why. Maybe a problem caused by the ground animation adjustments?

2021-05-20 22:46 UTC, swoolcock approved these changes
Looks fine to me.

2021-05-21 17:43 UTC, frenzibyte commented
The mentioned point:

> - The left tile of the ground occasionally spazzes, not sure why. Maybe a problem caused by the ground animation adjustments?

probably needs to be looked at, can check myself when I fully context-switch to scrolling algorithm logic but right now I think this can be blocked, unless this is immediate priority.

2021-05-21 17:44 UTC, frenzibyte requested changes
As above.

2021-05-21 19:01 UTC, frenzibyte approved these changes

2021-05-21 19:53 UTC, merged