Implement touch input support
Beamographic/rush pull request #164
Opened 2021-06-30 20:55 UTC by LumpBloom7

This PR aims to provide the possibility for players to play using a touch screen. 

In order to maintain consistency with keyboard users, and to allow for proper replay recording, the touch inputs are converted into `RushAction`s instead of being consumed by a drawable.

In this implementation, a custom `TouchEventManager` is used, which searches the input queue for drawables that has the `IKeyBindingTouchHandler` interface. The interface contains a function `GetTargetActionFor(Vector2 inputPosition)` to determine which high-level action (`TargetAction`) a touch is, which is then passed to `RushInputManager` so that it could attempt to convert that high-level action into a `RushAction`, based on the current state of actions. 

`RushInputManager` will attempt to find the lowest available action that matches the high-level action, and then presses it. In the event that there isn't any action that can be used, no actions will be pressed.

Right now, only two drawables attempt to convert touch inputs. Playfield is responsible for handling the touches on the entire screen, and returns `Ground` or `Air` based on the touch's Y position. FeverBar also handles it, and only returns `Fever`.

I've also temporarily included a custom `MouseButtonEventManager` as a quick and temporary way to test some of the handling logic, which will be removed once things are solidified.

2021-06-30 23:20 UTC, swoolcock requested changes
Mostly fine, haven't had a chance to test it.

2021-06-30 23:20 UTC, swoolcock commented on osu.Game.Rulesets.Rush/Input/RushInputManager.cs
> +        public void TryPressTouchAction(TouchSource source, TargetAction action)
Since the name has `Try` in it, please return a `bool` indicating whether it was successful.

2021-07-01 11:08 UTC, frenzibyte commented on osu.Game.Rulesets.Rush/Input/IKeyBindingTouchHandler.cs
> +        TargetAction GetTargetActionFor(Vector2 screenSpaceTouchPosition) => TargetAction.None;
Though this should probably accept a `TouchEvent` rather than just a position.

2021-07-03 12:47 UTC, swoolcock approved these changes

2022-10-22 20:13 UTC, merged